### ISSUE TITLE
Epsxe 2.0 Not Working w/ RegEmu32

### ISSUE THREAD

**Issue by shinra358** [KrossX/RegEmu32#1]
^Title.

**Comment by KrossX** [comment]
ePSXe 2.0 ?! =O

**Comment by shinra358** [comment]
https://www.youtube.com/watch?v=P3ALwKeSEYs

PS: btw, pokopom is bugged in 2.0 as well. But that probably is the fault of their side? Pressing ESC > continue during game, makes controller not work anymore.

**Comment by KrossX** [comment]
Done, give it a try.

About Pokopom, it's possibly a plugin bug (might affect pcsxr too). But, I cannot fix Pokopom bugs as my source is messed up with yet another pokopom rewrite...

**Comment by shinra358** [comment]
oh ok. pokopom worked great for me with tapcios hack in the previous epsxe though. brb, trying new update.

Edit: wait, is this still the recent uploading spot for your updates for your tools?: https://drive.google.com/folderview?id=0B1wssOeJs5_7czZ1WW93SzFxUWs&usp=drive_web 

If not, were can I test the new update?

**Comment by KrossX** [comment]
Yes, it's the v0.1-28 one. Note that for some reason, the zip files had v0.2... which was wrong.

**Comment by shinra358** [comment]
Ok, cool. It works now. But I don't see the dialgue for it anymore in the cmd window. Is that intentional? Also, in the ini, I don't see the changed values with the new plugins and new options and what not. I just see the old options and what is shown in the emu and how you have it set up, is not reflecting what is in the regemu32.ini.

**Comment by KrossX** [comment]
I replaced the patcher some time ago. It's a very simple one now, but very fast.

I just tested ePSXe 2.0 and it seems to be working fine. Without an INI file, it will show the setup guide and once that's done you'll have all the basic settings. Mess with the video settings and that section will show up in the INI file too.

**Comment by shinra358** [comment]
Ok, but I don't see the mention of the plugins i have running. I have petesgpu2.9 2.0 in but it still shows "VideoPlugin"="gpuPeteOpenGL2Tweak.dll"

I have my ff9 memory card in the first slot with the 2nd slot disabled and it's still showing me this:
"Memcard1"="E:\Users\T Dean Jr\My Documents\Games\CONSOLE\EMULATORS\SONY\Playstation\Playstation\memcards\Final Fantasy Anthology.mcr"
"Memcard1Enable"="1"
"Memcard2"="E:\Users\T Dean Jr\My Documents\Games\CONSOLE\EMULATORS\SONY\Playstation\Playstation\memcards\Final Fantasy VII pt-2.mcr"
"Memcard2Enable"="1"

So that means most settings are still going right to the real registry (unless they have an ini somewhere that stores info locally now).

**Comment by KrossX** [comment]
It's possible that you might have unpatched the exe. Delete the INI file and make sure a new one is created when you run the emu. If not, patch and try again.

**Comment by shinra358** [comment]
Ok. I deleted the ini. I deleted the exe of epsxe and patched it again and replaced. When I open up epsxe, all my settings are still the same (the way I want them). When I close epsxe, the regemu32.ini forms, but when I open it, it's blank. But epsxe still works and has all my settings as I want them. First start dialogue doesn't happen again either.

I know that the exe has been modified because the windows dialogue asking me if I want to run the file pops up again.

**Comment by KrossX** [comment]
Try with these files: [TEST](https://drive.google.com/open?id=0B1wssOeJs5_7T1UyaVN5eDFPQzQ)

**Comment by shinra358** [comment]
Ok, works. What different did you do than I?
I tried dropping the exe into regemu and I tried running the exe of the regemu :P

**Comment by KrossX** [comment]
Those are cleanly downloaded files, with the exe patched. I patched it by dropping **ePSXe.exe** into **Regemu.exe**. If you do that a second time however, it will get unpatched.

**Comment by shinra358** [comment]
Ok, cool. Thanks.
I'm still wanting this for Vanilla Sleeping Dogs so if you can make it work for that (or any of the illusion h games, feel free :P

**Comment by KrossX** [comment]
If the application complains about missing functions, just make an issue. But sometimes all the registry lines are made during installation and the game just reads them, making the ini with the proper entries would be up to the user.

**Comment by shinra358** [comment]
So I just tried it again by myself and only dropped the fresh exe in once. Still blank ini. What directory do you have it in? I think it may be a long director / directory space issue because it isn't working right when I do it mayself in my current directory I have it in. I think there was talk about this along time ago before.

**Comment by KrossX** [comment]
You can confirm that by trying again in a short directory path with no spaces.

**Comment by shinra358** [comment]
I tried it just on the root of the c drive. Nothing happening when I patch it and start epsxe. Old versions did work on things without issue. I dunno what's going on now.

**Comment by KrossX** [comment]
Make a folder on C called test (root might require admin rights) and copy the exe and the patcher there. Open a console window to that folder and use the patcher from there.

**Comment by KrossX** [comment]
Just to leave the points of what I did for the zip I gave you.
- Download ePSXe and Regemu again.
- Extract ePSXe.
- Extract Regemu into ePSXe's folder.
- Drag ePSXe.exe into Regemu.exe.

I suppose I could make CRC checks after extraction and after patch. Then you can compare with what you're getting. Somehow, something's not working properly in  your end and I cannot reproduce it.

**EDIT:**
- ePSXe200.zip **AFCEFE86**
- RegEmu32 v0.1-28.zip **00A76567**
- Regemu32.dll **1626223E**
- Regemu32.exe **09DAF8EC**
- ePSXe.exe **492A1109**
- ePSXe.exe **D4CD8C5D** (patched)

**Comment by shinra358** [comment]
so the whole process has to take place in epsxe's folder? I've just been extracting the emu exe, regemu dll, and regemu exe into a newly created folder and dragging it in the the regemu exe from there.

**Comment by KrossX** [comment]
No, it doesn't have to. But I've detailed the process of what I did so you can try and reproduce the results. I've done it again and added the CRCs so that you can compare them.

**Comment by shinra358** [comment]
all of the crcs are as you wrote them. viewed them from a winrar archive. after patched, the epsxe exe retains the same crc. so for some reason the program isn't patching. maybe the dialogue was a good idea to see what was going on. Here's a video proving that I did it like I was supposed to:

https://youtu.be/DnI6W8242V0

**Comment by KrossX** [comment]
lol, all you did was right. I am concerned with the popup asking for authorization though.

Anyhow, try and do the same but instead of drag and drop use the console/terminal. You'll get the feedback from the program to tell you if something was patched or not. Also, try from a normal terminal and from a terminal with admin rights.

In the mean time, I'll see about giving you a build of the patcher with plenty of them dialogs.

**Comment by shinra358** [comment]
That popup usually happens when I get a file from someone else's computer. That's normal.

I dragged teh regemu.exe on to epsxe.exe instead and all it did was start the emulator.

If I start as admin the regemu.exe, a console appears and then quickly disappears. Does the same as if I start it without admin rights.

**Comment by KrossX** [comment]
I think I found the bug. Rename the folder where you extracted Regemu to ASD or something else. Make sure it doesn't have Regemu in its name.

PS: Dragging regemu into epsxe is the equivalent to running epsxe with regemu.exe in the command line.

**Comment by shinra358** [comment]
Yep, changing the folder name makes it work.

**Comment by KrossX** [comment]
New version uploaded. See if this one works please.

**Comment by shinra358** [comment]
Ok, it works now with the program name as the folder.

**Comment by KrossX** [comment]
Yay! Thanks for all the testing.

**Comment by shinra358** [comment]
np glad you figured it out!
